### ISSUE TITLE
Plugin not working on Pelican 3.7.1 on Python 3.5

### ISSUE THREAD

**Issue by elyezer** [magnunleno/pelican-podcast-feed#2]
Trying to run the dev server with `make devserver` it is raising the following stacktrace:

```
CRITICAL: TypeError: _create_new_feed() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/castalio/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/elyezer/.virtualenvs/castalio/lib/python3.5/site-packages/pelican/__init__.py", line 465, in main
    pelican.run()
  File "/home/elyezer/.virtualenvs/castalio/lib/python3.5/site-packages/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/home/elyezer/code/castaliopodcast.github.io/plugins/pelican-podcast-feed/pelican_podcast_feed.py", line 316, in generate_output
    writer.write_feed(self.episodes, self.context, self.feed_path)
  File "/home/elyezer/.virtualenvs/castalio/lib/python3.5/site-packages/pelican/writers.py", line 117, in write_feed
    feed = self._create_new_feed(feed_type, feed_title, context)
TypeError: _create_new_feed() takes 3 positional arguments but 4 were given
```

**Comment by elyezer** [comment]
It happens that pelican 3.7 change the signature of `_create_new_feed` now it accepts 3 arguments: feed_type, feed_tile and context. Versions prior to 3.7 accepts 2 arguments: feed_type and context.

Also the other failure is that the `unicode` is being used and there is no `unicode` on python 3 anymore.

The diff below are the changes I had to make in order to get the plugin running again:

```diff
diff --git a/plugins/pelican-podcast-feed/pelican_podcast_feed.py b/plugins/pelican-podcast-feed/pelican_podcast_feed.py
index 0e90bcb..0085017 100644
--- a/plugins/pelican-podcast-feed/pelican_podcast_feed.py
+++ b/plugins/pelican-podcast-feed/pelican_podcast_feed.py
@@ -8,6 +8,7 @@ iTunes Feed Generator for Pelican.
 from __future__ import unicode_literals


+import six
 from jinja2 import Markup
 from pelican import signals
 from pelican.writers import Writer
@@ -159,12 +160,12 @@ class PodcastFeed(Rss201rev2Feed):
             if key == 'description':
                 content = item[key]
                 handler.startElement('description', {})
-                if not isinstance(content, unicode):
-                    content = unicode(content, handler._encoding)
+                if not isinstance(content, six.text_type):
+                    content = six.text_type(content, handler._encoding)
                 content = content.replace("<html><body>", "")
                 handler._write(content)
                 handler.endElement('description')
-            elif type(item[key]) in (str, unicode):
+            elif isinstance(item[key], six.text_type):
                 handler.addQuickElement(key, item[key])
             elif type(item[key]) is dict:
                 handler.addQuickElement(key, attrs=item[key])
@@ -179,7 +180,7 @@ class iTunesWriter(Writer):
         """Class initializer"""
         super(iTunesWriter, self).__init__(*args, **kwargs)

-    def _create_new_feed(self, feed_type, context):
+    def _create_new_feed(self, feed_type, feed_title, context):
         """Helper function (called by the super class) which will initialize
         the PodcastFeed object."""
         self.context = context
```

I will think more about how to better solve the difference of the "private" method tomorrow. Hopefully I can make a PR to fix it.

**Comment by elyezer** [comment]
The final solution is here https://github.com/CastalioPodcast/CastalioPodcast.github.io/pull/74

With those changes the plugin supports both Python 2 and 3 and Pelican 3.5+.

**Comment by magnunleno** [comment]
Merged your changes. Thanks

**Comment by elyezer** [comment]
I am glad you like the solution. Thank you.
